#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    May 12, 2022 09:09:53 AM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from Backend.admin import Admin
import tkinter.messagebox as tsmg


import all_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("1200x700+309+161")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("E-Tracking - Administrator - Add Station")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#c1cb50")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        
        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0, rely=0, height=700, width=1200)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        photo_location = "img/Background-PNG-Clipart-Background.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.267, rely=0.071, relheight=0.864
                , relwidth=0.464)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#ffffff")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label_add_station = tk.Label(self.Frame2)
        self.Label_add_station.place(relx=0.197, rely=0.033, height=96, width=362)
        self.Label_add_station.configure(activebackground="#f9f9f9")
        self.Label_add_station.configure(background="#ffffff")
        self.Label_add_station.configure(compound='left')
        self.Label_add_station.configure(disabledforeground="#a3a3a3")
        self.Label_add_station.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.Label_add_station.configure(foreground="#000000")
        self.Label_add_station.configure(highlightbackground="#d9d9d9")
        self.Label_add_station.configure(highlightcolor="black")
        self.Label_add_station.configure(text='''Add Station''')

        self.Label_station_ID = tk.Label(self.Frame2)
        self.Label_station_ID.place(relx=0.162, rely=0.248, height=26, width=122)
        self.Label_station_ID.configure(activebackground="#f9f9f9")
        self.Label_station_ID.configure(anchor='w')
        self.Label_station_ID.configure(background="#ffffff")
        self.Label_station_ID.configure(compound='left')
        self.Label_station_ID.configure(disabledforeground="#a3a3a3")
        self.Label_station_ID.configure(foreground="#000000")
        self.Label_station_ID.configure(highlightbackground="#d9d9d9")
        self.Label_station_ID.configure(highlightcolor="black")
        self.Label_station_ID.configure(text='''Station's ID''')

        self.Label_name = tk.Label(self.Frame2)
        self.Label_name.place(relx=0.162, rely=0.364, height=26, width=42)
        self.Label_name.configure(activebackground="#f9f9f9")
        self.Label_name.configure(anchor='w')
        self.Label_name.configure(background="#ffffff")
        self.Label_name.configure(compound='left')
        self.Label_name.configure(disabledforeground="#a3a3a3")
        self.Label_name.configure(foreground="#000000")
        self.Label_name.configure(highlightbackground="#d9d9d9")
        self.Label_name.configure(highlightcolor="black")
        self.Label_name.configure(text='''Name''')

        self.Label_address = tk.Label(self.Frame2)
        self.Label_address.place(relx=0.162, rely=0.479, height=26
                , width=122)
        self.Label_address.configure(activebackground="#f9f9f9")
        self.Label_address.configure(anchor='w')
        self.Label_address.configure(background="#ffffff")
        self.Label_address.configure(compound='left')
        self.Label_address.configure(disabledforeground="#a3a3a3")
        self.Label_address.configure(foreground="#000000")
        self.Label_address.configure(highlightbackground="#d9d9d9")
        self.Label_address.configure(highlightcolor="black")
        self.Label_address.configure(text='''Adress''')


        self.Entry_station_ID = tk.Entry(self.Frame2)
        self.Entry_station_ID.place(relx=0.18, rely=0.298, height=34, relwidth=0.654)
        self.Entry_station_ID.configure(background="white")
        self.Entry_station_ID.configure(disabledforeground="#a3a3a3")
        self.Entry_station_ID.configure(font="TkFixedFont")
        self.Entry_station_ID.configure(foreground="#000000")
        self.Entry_station_ID.configure(highlightbackground="#d9d9d9")
        self.Entry_station_ID.configure(highlightcolor="black")
        self.Entry_station_ID.configure(insertbackground="black")
        self.Entry_station_ID.configure(selectbackground="#c4c4c4")
        self.Entry_station_ID.configure(selectforeground="black")

        self.Entry_name = tk.Entry(self.Frame2)
        self.Entry_name.place(relx=0.18, rely=0.413, height=34, relwidth=0.654)
        self.Entry_name.configure(background="white")
        self.Entry_name.configure(disabledforeground="#a3a3a3")
        self.Entry_name.configure(font="TkFixedFont")
        self.Entry_name.configure(foreground="#000000")
        self.Entry_name.configure(highlightbackground="#d9d9d9")
        self.Entry_name.configure(highlightcolor="black")
        self.Entry_name.configure(insertbackground="black")
        self.Entry_name.configure(selectbackground="#c4c4c4")
        self.Entry_name.configure(selectforeground="black")

        self.Entry_address = tk.Entry(self.Frame2)
        self.Entry_address.place(relx=0.18, rely=0.545, height=34, relwidth=0.654)
        self.Entry_address.configure(background="white")
        self.Entry_address.configure(disabledforeground="#a3a3a3")
        self.Entry_address.configure(font="TkFixedFont")
        self.Entry_address.configure(foreground="#000000")
        self.Entry_address.configure(highlightbackground="#d9d9d9")
        self.Entry_address.configure(highlightcolor="black")
        self.Entry_address.configure(insertbackground="black")
        self.Entry_address.configure(selectbackground="#c4c4c4")
        self.Entry_address.configure(selectforeground="black")
        

     

        self.Button_add = tk.Button(self.Frame2)
        self.Button_add.place(relx=0.305, rely=0.793, height=43, width=76)
        self.Button_add.configure(activebackground="beige")
        self.Button_add.configure(activeforeground="#000000")
        self.Button_add.configure(background="#0080ff")
        self.Button_add.configure(compound='left')
        self.Button_add.configure(disabledforeground="#a3a3a3")
        self.Button_add.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button_add.configure(foreground="#ffffff")
        self.Button_add.configure(highlightbackground="#d9d9d9")
        self.Button_add.configure(highlightcolor="black")
        self.Button_add.configure(pady="0")
        self.Button_add.configure(text='''Add''')
        self.Button_add.configure(command=self.add_btn)

        self.Button_cancle = tk.Button(self.Frame2)
        self.Button_cancle.place(relx=0.575, rely=0.793, height=43, width=76)
        self.Button_cancle.configure(activebackground="beige")
        self.Button_cancle.configure(activeforeground="#000000")
        self.Button_cancle.configure(background="#dc1d25")
        self.Button_cancle.configure(compound='left')
        self.Button_cancle.configure(disabledforeground="#a3a3a3")
        self.Button_cancle.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button_cancle.configure(foreground="#ffffff")
        self.Button_cancle.configure(highlightbackground="#d9d9d9")
        self.Button_cancle.configure(highlightcolor="black")
        self.Button_cancle.configure(pady="0")
        self.Button_cancle.configure(text='''Cancel''')
        self.Button_cancle.configure(command=self.cancle_btn)
        
    def add_btn(self):
        station = self.Entry_station_ID.get()
        name = self.Entry_name.get()
        address = self.Entry_address.get()
        if station == "" or name == "" or address == "":
            tsmg.showerror('Error','Error')
        else:
            if (Admin.create_station(station, name, address)) != True :
                tsmg.showerror('Create failed','Invalid Value or Station Already have!')
            else:
                tsmg.showinfo('Create Complate!', 'Create Station Complate!')
            

    def cancle_btn(self):
        self.top.destroy() 
        all_support.main_administrator_page()
        if __name__ == '__main__':
            all_support.main_administrator_page()    


def start_up():
    all_support.main_add_station_page()

if __name__ == '__main__':
    all_support.main_add_station_page()




