#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    May 12, 2022 07:16:36 AM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import all_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("1200x700+316+148")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("E-Tracking App - Administrator")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#c1cb50")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        
        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0, rely=0, height=700, width=1200)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        photo_location = "img/Background-PNG-Clipart-Background.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.275, rely=0.071, relheight=0.864
                , relwidth=0.463)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#ffffff")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Button_add_employee = tk.Button(self.Frame2)
        self.Button_add_employee.place(relx=0.320, rely=0.190, height=100, width=200)
        self.Button_add_employee.configure(activebackground="beige")
        self.Button_add_employee.configure(activeforeground="#000000")
        self.Button_add_employee.configure(background="#d9d9d9")
        self.Button_add_employee.configure(compound='left')
        self.Button_add_employee.configure(disabledforeground="#a3a3a3")
        self.Button_add_employee.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button_add_employee.configure(foreground="#400040")
        self.Button_add_employee.configure(highlightbackground="#d9d9d9")
        self.Button_add_employee.configure(highlightcolor="black")
        self.Button_add_employee.configure(pady="0")
        self.Button_add_employee.configure(text='''Add Employee''')
        self.Button_add_employee.configure(command=self.create_em_btn)
        
        # photo_location = "img/marine_button (Custom).png"
        # global _img1
        # _img1 = tk.PhotoImage(file=photo_location)
        # self.Button_add_employee.configure(image=_img1)

        self.Button_update_employee = tk.Button(self.Frame2)
        self.Button_update_employee.place(relx=0.320, rely=0.391, height=100, width=200)
        self.Button_update_employee.configure(activebackground="beige")
        self.Button_update_employee.configure(activeforeground="#000000")
        self.Button_update_employee.configure(background="#c0c0c0")
        self.Button_update_employee.configure(compound='left')
        self.Button_update_employee.configure(disabledforeground="#a3a3a3")
        self.Button_update_employee.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button_update_employee.configure(foreground="#400040")
        self.Button_update_employee.configure(highlightbackground="#d9d9d9")
        self.Button_update_employee.configure(highlightcolor="black")
        self.Button_update_employee.configure(pady="0")
        self.Button_update_employee.configure(text='''Update Emploeyy''')
        self.Button_update_employee.configure(command=self.update_em_btn)
        # self.Button_update_employee.configure(image=_img1)
        
        
        self.Button_create_station = tk.Button(self.Frame2)
        self.Button_create_station.place(relx=0.320, rely=0.591, height=100, width=200)
        self.Button_create_station.configure(activebackground="beige")
        self.Button_create_station.configure(activeforeground="#000000")
        self.Button_create_station.configure(background="#c0c0c0")
        self.Button_create_station.configure(compound='left')
        self.Button_create_station.configure(disabledforeground="#a3a3a3")
        self.Button_create_station.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button_create_station.configure(foreground="#400040")
        self.Button_create_station.configure(highlightbackground="#d9d9d9")
        self.Button_create_station.configure(highlightcolor="black")
        self.Button_create_station.configure(pady="0")
        self.Button_create_station.configure(text='''Create Station''')
        self.Button_create_station.configure(command=self.create_sta_btn)
        # self.Button_create_station.configure(image=_img1)
        
        self.Button_log_out = tk.Button(self.Frame1)
        self.Button_log_out.place(relx=0.883, rely=0.029, height=100, width=100)
        self.Button_log_out.configure(activebackground="beige")
        self.Button_log_out.configure(activeforeground="#000000")
        self.Button_log_out.configure(background="#d9d9d9")
        self.Button_log_out.configure(compound='left')
        self.Button_log_out.configure(disabledforeground="#a3a3a3")
        self.Button_log_out.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button_log_out.configure(foreground="#ffffff")
        self.Button_log_out.configure(highlightbackground="#d9d9d9")
        self.Button_log_out.configure(highlightcolor="black")
        self.Button_log_out.configure(pady="0")
        self.Button_log_out.configure(text='''Log Out''')
        self.Button_log_out.configure(command=self.log_out_btn)
        photo_location = "img/Log Out (Custom).png"
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Button_log_out.configure(image=_img4)


    def log_out_btn(self):
        self.top.destroy() 
        all_support.main_login_page1()
        if __name__ == '__main__':
            all_support.main_login_page1()

    def create_sta_btn(self):
        self.top.destroy() 
        all_support.main_add_station_page()
        if __name__ == '__main__':
            all_support.main_add_station_page()

    def create_em_btn(self):
        self.top.destroy() 
        all_support.main_add_employee_1()
        if __name__ == '__main__':
            all_support.main_add_employee_1()

    
    def update_em_btn(self):
        self.top.destroy() 
        all_support.main_update_employee_page()
        if __name__ == '__main__':
            all_support.main_update_employee_page()



def start_up():
    all_support.main_administrator_page()

if __name__ == '__main__':
    all_support.main_administrator_page()




