#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    May 11, 2022 11:51:36 PM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from Backend.customer import Customer
from Backend.constants import AccoutStatus, AccoutType
from Backend.employee import Employee
from tkinter.constants import *
import tkinter.messagebox as tsmg

import all_support

class Toplevel1:
        def __init__(self, top=None):
                '''This class configures and populates the toplevel window.
                top is the toplevel containing window.'''
                _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
                _fgcolor = '#000000'  # X11 color: 'black'
                _compcolor = 'gray40' # X11 color: #666666
                _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
                _ana2color = 'beige' # X11 color: #f5f5dc
                _tabfg1 = 'black' 
                _tabfg2 = 'black' 
                _tabbg1 = 'grey75' 
                _tabbg2 = 'grey89' 
                _bgmode = 'light' 

                top.geometry("1200x700+296+151")
                top.minsize(148, 1)
                top.maxsize(1924, 1055)
                top.resizable(1,  1)
                top.title("E-Tracking App - for employees - create user")
                top.configure(background="#d9d9d9")
                top.configure(highlightbackground="#d9d9d9")
                top.configure(highlightcolor="black")

                self.top = top

                self.Frame1 = tk.Frame(self.top)
                self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
                self.Frame1.configure(relief='groove')
                self.Frame1.configure(borderwidth="2")
                self.Frame1.configure(relief="groove")
                self.Frame1.configure(background="#0080ff")
                self.Frame1.configure(highlightbackground="#d9d9d9")
                self.Frame1.configure(highlightcolor="black")
                
                self.Label1 = tk.Label(self.Frame1)
                self.Label1.place(relx=0, rely=0, height=700, width=1200)
                self.Label1.configure(anchor='w')
                self.Label1.configure(background="#d9d9d9")
                self.Label1.configure(compound='left')
                self.Label1.configure(cursor="fleur")
                self.Label1.configure(disabledforeground="#a3a3a3")
                self.Label1.configure(foreground="#000000")
                photo_location = "img/employee_bg (Custom).png"
                global _img0
                _img0 = tk.PhotoImage(file=photo_location)
                self.Label1.configure(image=_img0)

                self.Frame_create_user = tk.Frame(self.Frame1)
                self.Frame_create_user.place(relx=0.317, rely=0.086, relheight=0.81
                        , relwidth=0.403)
                self.Frame_create_user.configure(relief='groove')
                self.Frame_create_user.configure(borderwidth="2")
                self.Frame_create_user.configure(relief="groove")
                self.Frame_create_user.configure(background="#ffffff")
                self.Frame_create_user.configure(highlightbackground="#d9d9d9")
                self.Frame_create_user.configure(highlightcolor="black")

                self.Label_create_user = tk.Label(self.Frame_create_user)
                self.Label_create_user.place(relx=0.062, rely=0.037, height=131
                        , width=422)
                self.Label_create_user.configure(activebackground="#f9f9f9")
                self.Label_create_user.configure(background="#ffffff")
                self.Label_create_user.configure(compound='left')
                self.Label_create_user.configure(disabledforeground="#a3a3a3")
                self.Label_create_user.configure(font="-family {Segoe UI} -size 20 -weight bold")
                self.Label_create_user.configure(foreground="#000000")
                self.Label_create_user.configure(highlightbackground="#d9d9d9")
                self.Label_create_user.configure(highlightcolor="black")
                self.Label_create_user.configure(text='''Create User's Account''')

                self.Button_create_user = tk.Button(self.Frame_create_user)
                self.Button_create_user.place(relx=0.372, rely=0.811, height=43
                        , width=116)
                self.Button_create_user.configure(activebackground="#c0c0c0")
                self.Button_create_user.configure(activeforeground="#000000")
                self.Button_create_user.configure(background="#0080ff")
                self.Button_create_user.configure(compound='left')
                self.Button_create_user.configure(cursor="fleur")
                self.Button_create_user.configure(disabledforeground="#a3a3a3")
                self.Button_create_user.configure(font="-family {Segoe UI} -size 9 -weight bold")
                self.Button_create_user.configure(foreground="#ffffff")
                self.Button_create_user.configure(highlightbackground="#d9d9d9")
                self.Button_create_user.configure(highlightcolor="black")
                self.Button_create_user.configure(pady="0")
                self.Button_create_user.configure(text='''Create''')
                self.Button_create_user.configure(command=self.create_user_btn)

                self.Entry_person_ID = tk.Entry(self.Frame_create_user)
                self.Entry_person_ID.place(relx=0.165, rely=0.37, height=24
                        , relwidth=0.669)
                self.Entry_person_ID.configure(background="white")
                self.Entry_person_ID.configure(disabledforeground="#a3a3a3")
                self.Entry_person_ID.configure(font="TkFixedFont")
                self.Entry_person_ID.configure(foreground="#000000")
                self.Entry_person_ID.configure(insertbackground="black")

                self.Label_person_ID = tk.Label(self.Frame_create_user)
                self.Label_person_ID.place(relx=0.165, rely=0.3, height=26, width=92)
                self.Label_person_ID.configure(anchor='w')
                self.Label_person_ID.configure(background="#ffffff")
                self.Label_person_ID.configure(compound='left')
                self.Label_person_ID.configure(disabledforeground="#a3a3a3")
                self.Label_person_ID.configure(font="-family {Segoe UI} -size 9")
                self.Label_person_ID.configure(foreground="#000000")
                self.Label_person_ID.configure(text='''Person's ID''')

                self.Label_name = tk.Label(self.Frame_create_user)
                self.Label_name.place(relx=0.165, rely=0.423, height=26, width=52)
                self.Label_name.configure(anchor='w')
                self.Label_name.configure(background="#ffffff")
                self.Label_name.configure(compound='left')
                self.Label_name.configure(disabledforeground="#a3a3a3")
                self.Label_name.configure(font="-family {Segoe UI} -size 9")
                self.Label_name.configure(foreground="#000000")
                self.Label_name.configure(text='''Name''')

                self.Entry_name = tk.Entry(self.Frame_create_user)
                self.Entry_name.place(relx=0.165, rely=0.494, height=24, relwidth=0.669)
                self.Entry_name.configure(background="white")
                self.Entry_name.configure(disabledforeground="#a3a3a3")
                self.Entry_name.configure(font="TkFixedFont")
                self.Entry_name.configure(foreground="#000000")
                self.Entry_name.configure(insertbackground="black")

                self.Label_phone_number = tk.Label(self.Frame_create_user)
                self.Label_phone_number.place(relx=0.165, rely=0.547, height=26
                        , width=112)
                self.Label_phone_number.configure(anchor='w')
                self.Label_phone_number.configure(background="#ffffff")
                self.Label_phone_number.configure(compound='left')
                self.Label_phone_number.configure(disabledforeground="#a3a3a3")
                self.Label_phone_number.configure(font="-family {Segoe UI} -size 9")
                self.Label_phone_number.configure(foreground="#000000")
                self.Label_phone_number.configure(text='''Phone Number''')

                self.Entry_phone_number = tk.Entry(self.Frame_create_user)
                self.Entry_phone_number.place(relx=0.165, rely=0.617, height=24
                        , relwidth=0.669)
                self.Entry_phone_number.configure(background="white")
                self.Entry_phone_number.configure(disabledforeground="#a3a3a3")
                self.Entry_phone_number.configure(font="TkFixedFont")
                self.Entry_phone_number.configure(foreground="#000000")
                self.Entry_phone_number.configure(insertbackground="black")
                
                
                

        def create_user_btn(self):
                phone_number = self.Entry_phone_number.get()
                username  = self.Entry_person_ID.get()
                name = self.Entry_name.get()
                
                print(Customer.All_Customer_list)

                if phone_number == "" or username == "" or name == "":
                        tsmg.showerror('Insert Fail','Please Enter all filed!')
                else:
                        if (Employee.create_customer(username, name, phone_number, AccoutType.Customer, username, phone_number, AccoutStatus.Active)) == None:
                                tsmg.showinfo('Create Complate!', 'Customer have been create!!')
                                self.top.destroy() 
                                all_support.main_backend_page1()
                                if __name__ == '__main__':
                                        all_support.main_backend_page1()
                        else:
                                tsmg.showerror('Error', 'Invalid Input or Already have Customer!!')
            
                


def start_up():
    all_support.main_create_user_page1()

if __name__ == '__main__':
    all_support.main_create_user_page1()




