#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    May 11, 2022 08:55:23 PM +07  platform: Windows NT

import sys

sys.path.append('/Backend/')
from Backend.admin import Admin 

import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import tkinter.messagebox as tsmg


import login_page_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("1200x700+330+164")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ff8080")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Frame_login = tk.Frame(self.Frame1)
        self.Frame_login.place(relx=0.325, rely=0.043, relheight=0.82
                , relwidth=0.345)
        self.Frame_login.configure(relief='groove')
        self.Frame_login.configure(borderwidth="2")
        self.Frame_login.configure(relief="groove")
        self.Frame_login.configure(background="#ffffff")
        self.Frame_login.configure(highlightbackground="#d9d9d9")
        self.Frame_login.configure(highlightcolor="black")

        self.Label_login = tk.Label(self.Frame_login)
        self.Label_login.place(relx=0.072, rely=0.035, height=76, width=352)
        self.Label_login.configure(activebackground="#ffffff")
        self.Label_login.configure(background="#ffffff")
        self.Label_login.configure(compound='left')
        self.Label_login.configure(disabledforeground="#ffffff")
        self.Label_login.configure(font="-family {Segoe UI} -size 18")
        self.Label_login.configure(foreground="#000000")
        self.Label_login.configure(highlightbackground="#d9d9d9")
        self.Label_login.configure(highlightcolor="black")
        self.Label_login.configure(text='''Log In''')

        self.Entry_user = tk.Entry(self.Frame_login)
        self.Entry_user.place(relx=0.121, rely=0.366, height=34, relwidth=0.778)
        self.Entry_user.configure(background="white")
        self.Entry_user.configure(borderwidth="5")
        self.Entry_user.configure(disabledforeground="#a3a3a3")
        self.Entry_user.configure(font="-family {Segoe UI} -size 10")
        self.Entry_user.configure(foreground="#000000")
        self.Entry_user.configure(highlightbackground="#d9d9d9")
        self.Entry_user.configure(highlightcolor="black")
        self.Entry_user.configure(insertbackground="black")
        self.Entry_user.configure(selectbackground="#c4c4c4")
        self.Entry_user.configure(selectforeground="black")

        self.Entry_password = tk.Entry(self.Frame_login)
        self.Entry_password.place(relx=0.121, rely=0.505, height=34
                , relwidth=0.778)
        self.Entry_password.configure(background="white")
        self.Entry_password.configure(borderwidth="5")
        self.Entry_password.configure(disabledforeground="#a3a3a3")
        self.Entry_password.configure(font="TkFixedFont")
        self.Entry_password.configure(foreground="#000000")
        self.Entry_password.configure(highlightbackground="#d9d9d9")
        self.Entry_password.configure(highlightcolor="black")
        self.Entry_password.configure(insertbackground="black")
        self.Entry_password.configure(selectbackground="#c4c4c4")
        self.Entry_password.configure(selectforeground="black")
        self.Entry_password.configure(show="*")

        self.Label_user = tk.Label(self.Frame_login)
        self.Label_user.place(relx=0.121, rely=0.314, height=26, width=42)
        self.Label_user.configure(activebackground="#f9f9f9")
        self.Label_user.configure(anchor='w')
        self.Label_user.configure(background="#ffffff")
        self.Label_user.configure(compound='left')
        self.Label_user.configure(disabledforeground="#a3a3a3")
        self.Label_user.configure(font="-family {Segoe UI} -size 9")
        self.Label_user.configure(foreground="#000000")
        self.Label_user.configure(highlightbackground="#d9d9d9")
        self.Label_user.configure(highlightcolor="black")
        self.Label_user.configure(text='''User''')

        self.Label_password = tk.Label(self.Frame_login)
        self.Label_password.place(relx=0.121, rely=0.453, height=26, width=82)
        self.Label_password.configure(activebackground="#f9f9f9")
        self.Label_password.configure(anchor='w')
        self.Label_password.configure(background="#ffffff")
        self.Label_password.configure(compound='left')
        self.Label_password.configure(disabledforeground="#a3a3a3")
        self.Label_password.configure(font="-family {Segoe UI} -size 9")
        self.Label_password.configure(foreground="#000000")
        self.Label_password.configure(highlightbackground="#d9d9d9")
        self.Label_password.configure(highlightcolor="black")
        self.Label_password.configure(text='''Password''')

        self.Button_login = tk.Button(self.Frame_login)
        self.Button_login.place(relx=0.386, rely=0.679, height=53, width=96)
        self.Button_login.configure(activebackground="#008040")
        self.Button_login.configure(activeforeground="white")
        self.Button_login.configure(activeforeground="#000000")
        self.Button_login.configure(background="#00d776")
        self.Button_login.configure(compound='left')
        self.Button_login.configure(disabledforeground="#008000")
        self.Button_login.configure(font="-family {Segoe UI} -size 9")
        self.Button_login.configure(foreground="#ffffff")
        self.Button_login.configure(highlightbackground="#000000")
        self.Button_login.configure(highlightcolor="black")
        self.Button_login.configure(pady="0")
        self.Button_login.configure(text='''Log In''')
        self.Button_login.configure(command=self.Main_login)


        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    def Main_login(self):
        print(self.Entry_user.get())
        print(self.Entry_password.get())

        admin = Admin.get_admin(self.Entry_user.get(), self.Entry_password.get())
        print(admin)

    def Main_login_fail(self):
        tsmg.showerror('login failed','can not log in, please try again!')




def start_up():
    login_page_support.main()

if __name__ == '__main__':
    login_page_support.main()




